stages:
  - test
  - deploy

before_script:
  - asdf install
  - pnpm install

test:
  script:
    - pnpm lint:js
    - pnpm lint:ts
  except:
    - develop
    - staging
    - master

deploy_staging:
  stage: deploy
  script:
    - pnpm build:staging:mp-weixin
    - pnpm deploy:staging:mp-weixin
  only:
    - staging

deploy_production:
  stage: deploy
  script:
    - pnpm build:production:mp-weixin
    - pnpm deploy:production:mp-weixin
  only:
    - production
